In [196]:
function [theta, J_history] = gradientDescentMulti(X, y, theta, alpha, num_iters)
%GRADIENTDESCENTMULTI Performs gradient descent to learn theta
%   theta = GRADIENTDESCENTMULTI(x, y, theta, alpha, num_iters) updates theta by
%   taking num_iters gradient steps with learning rate alpha

% Initialize some useful values
m = length(y); % number of training examples
J_history = zeros(num_iters, 1);

for iter = 1:num_iters

    temp = X * theta;
    error = temp - y;
    newX = error' * X;
    theta = theta - ((alpha/m) * newX');
    % ====================== YOUR CODE HERE ======================
    % Instructions: Perform a single gradient step on the parameter vector
    %               theta. 
    %
    % Hint: While debugging, it can be useful to print out the values
    %       of the cost function (computeCostMulti) and gradient here.
    %











    % ============================================================

    % Save the cost J in every iteration    
    J_history(iter) = computeCostMulti(X, y, theta);

end

end

SyntaxError: invalid syntax (<ipython-input-196-e9e18ee8336f>, line 7)

In [ ]:
def gadientDescentMulti(X, y, theta=[], alpha, num_iters =10): #theta as series
    # GRADIENT DESCENT FOR NEURAL NETWORKS
    # ADIENTDESCENTMULTI Performs gradient descent to predict best theta
    
    # X  := features represented as a pandas dataframe | convert non numeric categorical and ordinal featuires into numeric features
    # y  := output labels vector as a pandas series
    # theta := define  initial theta
    # I := num of observations = len(X)
    # J := number of features 
    # i = 1,2,...I 
    # j = 1,2,...J
    # num_iters = max num of interation to get appropriate output theta
    # alpha := (positive float value) determine rate of converge, can be from  [...,0.01,0.03,0.1,0.3,..]
    
    
    # X_scaled := X scaled by (X-mean(X))/(max(X)-min(X)) such that each X[:,j] feature
    # y_scaled : y scaled as above
    # generally 1 < max(X_scaled[:,J]) < 3 and -3 < min(X_scaled[:,J]) < -1 represent  
    
    # make a temp list: feature_classify = []
    # len(feature_classify) = num of features = J
    # len(test each feature X[:,j] is 
    
    # simple algorithm for theta initialization
    # theta = panda series similar to X_scaled.mean(axis=1)  #good for linear approximation
     
    # define cost function #assuming linear

    return theta #best prediction

In [ ]:
function J = computeCostMulti(X, y, theta)
%COMPUTECOSTMULTI Compute cost for linear regression with multiple variables
%   J = COMPUTECOSTMULTI(X, y, theta) computes the cost of using theta as the
%   parameter for linear regression to fit the data points in X and y

% Initialize some useful values
m = length(y); % number of training examples

% You need to return the following variables correctly 
J = 0;

% ====================== YOUR CODE HERE ======================
% Instructions: Compute the cost of a particular choice of theta
%               You should set J to the cost.


J = (1 / (2*m) ) * sum(((X * theta)-y).^2);



% =========================================================================

end

In [ ]:
inbuilt scikit stochastic gradient descent
http://scikit-learn.org/stable/modules/sgd.html

In [220]:
import pandas as pd
import matplotlib as plt
import numpy as np

In [226]:
raw_data = pd.read_csv('/home/triloq/Dropbox/life_guide/ML/ML_andrew_ng/machine-learning-ex1/ex1/ex1data1.txt',header=None,names=['xi','yi'])


raw_data.head(10)

xi       yi
0  6.1101  17.5920
1  5.5277   9.1302
2  8.5186  13.6620
3  7.0032  11.8540
4  5.8598   6.8233
5  8.3829  11.8860
6  7.4764   4.3483
7  8.5781  12.0000
8  6.4862   6.5987
9  5.0546   3.8166

In [201]:
f =[raw_data.dtypes]
f

[xi    float64
 yi    float64
 dtype: object]

In [ ]:
#write an algo to transform non_numeric features to numeric and ignore certain feature not needed

In [227]:
#raw_data = raw_data.as_matrix()
cost=0
num_obs=len(raw_data)
num_obs


97

In [203]:
isinstance(raw_data, pd.DataFrame)

True

In [ ]:
#extractedData = data[:,[1,9]]

In [241]:
X = raw_data.iloc[:,0:-1]
Y = raw_data.iloc[:,-1]
X.head()
Y.head()

0    17.5920
1     9.1302
2    13.6620
3    11.8540
4     6.8233
Name: yi, dtype: float64

In [242]:
X['x0'] = pd.DataFrame(np.ones(num_obs))
X
#DataFrame.insert(loc, column, value, allow_duplicates=False)[source]

xi   x0
0    6.1101  1.0
1    5.5277  1.0
2    8.5186  1.0
3    7.0032  1.0
4    5.8598  1.0
5    8.3829  1.0
6    7.4764  1.0
7    8.5781  1.0
8    6.4862  1.0
9    5.0546  1.0
10   5.7107  1.0
11  14.1640  1.0
12   5.7340  1.0
13   8.4084  1.0
14   5.6407  1.0
15   5.3794  1.0
16   6.3654  1.0
17   5.1301  1.0
18   6.4296  1.0
19   7.0708  1.0
20   6.1891  1.0
21  20.2700  1.0
22   5.4901  1.0
23   6.3261  1.0
24   5.5649  1.0
25  18.9450  1.0
26  12.8280  1.0
27  10.9570  1.0
28  13.1760  1.0
29  22.2030  1.0
..      ...  ...
67  10.2360  1.0
68   5.4994  1.0
69  20.3410  1.0
70  10.1360  1.0
71   7.3345  1.0
72   6.0062  1.0
73   7.2259  1.0
74   5.0269  1.0
75   6.5479  1.0
76   7.5386  1.0
77   5.0365  1.0
78  10.2740  1.0
79   5.1077  1.0
80   5.7292  1.0
81   5.1884  1.0
82   6.3557  1.0
83   9.7687  1.0
84   6.5159  1.0
85   8.5172  1.0
86   9.1802  1.0
87   6.0020  1.0
88   5.5204  1.0
89   5.0594  1.0
90   5.7077  1.0
91   7.6366  1.0
92   5.8707  1.0
93   5.3054  1.0
94   8.2934  1.0
95  13.3940  1.0
96   5.4369  1.0

[97 rows x 2 columns]

In [275]:
theta =np.matrix([0.5,0.5])
theta

matrix([[ 0.5,  0.5]])

In [244]:
X=np.matrix(X.values)
Y=np.matrix(Y.values)

In [245]:
X.shape, theta.shape, Y.shape  

((97, 2), (1, 2), (1, 97))

In [252]:
error_squared = np.power(((X * theta.T) - Y), 2)
error_squared


matrix([[ 174.75850603,   22.63690625,   86.29714732, ...,   17.87458211,
           21.92792082,   14.10245992],
        [ 185.95113107,   26.77638123,   94.21400601, ...,   14.52425487,
           26.00479783,   11.14598316],
        [ 132.16050955,    9.20702778,   57.24599711, ...,   35.41858524,
            8.75691466,   30.0177047 ],
        ..., 
        [ 135.8917359 ,   10.21097152,   59.7105638 , ...,   33.52640353,
            9.73665327,   28.27781545],
        [  64.11657888,    0.20658583,   16.62423556, ...,   89.11694435,
            0.28049431,   80.41905385],
        [ 187.72743682,   27.45305437,   95.47959818, ...,   14.03321847,
           26.67171154,   10.71635064]])

In [249]:
def computeCostMulti(X_scaled, y_scaled, theta, num_obs):
    error_squared = np.power(((X_scaled * theta.T) - y_scaled), 2)
    return  np.sum(error_squared)/ (2 * num_obs)
    

In [253]:
computeCostMulti(X,Y,theta,num_obs)

1825.5313407358865

In [267]:
def gradientDescent(X, Y, theta, alpha, iters):  
    temp = np.matrix(np.zeros(theta.shape))
    parameters = int(theta.ravel().shape[1])
    cost = np.zeros(iters)

    for i in range(iters):
        error = (X * theta.T) - Y

        for j in range(parameters):
            term = np.multiply(error, X[:,j])
            temp[0,j] = theta[0,j] - ((alpha / len(X)) * np.sum(term))

        theta = temp
        cost[i] = computeCost(X, Y, theta)

    return theta, cost

In [254]:
temp = np.matrix(np.zeros(theta.shape))
parameters = int(theta.ravel().shape[1])
temp,parameters

(matrix([[ 0.,  0.]]), 2)

In [278]:
iters=10

alpha =0.01

In [258]:
cost = np.zeros(iters)

In [279]:
for i in range(iters):
        error = (X * theta.T) - Y
        # print(error)
        for j in range(parameters):
            term = np.multiply(error, X[:,j])
            print(temp)
            temp[0,j] = theta[0,j] - ((alpha / len(X)) * np.sum(term))
        theta = temp
        cost[i] = computeCostMulti(X, Y, theta, num_obs)


[[ -2.12393241e+22  -2.13372049e+21]]
[[  1.67274487e+24  -2.13372049e+21]]
[[  1.67274487e+24   1.68045366e+23]]
[[ -1.31740322e+26   1.68045366e+23]]
[[ -1.31740322e+26  -1.32347443e+25]]
[[  1.03754690e+28  -1.32347443e+25]]
[[  1.03754690e+28   1.04232840e+27]]
[[ -8.17140526e+29   1.04232840e+27]]
[[ -8.17140526e+29  -8.20906293e+28]]
[[  6.43555142e+31  -8.20906293e+28]]
[[  6.43555142e+31   6.46520945e+30]]
[[ -5.06844548e+33   6.46520945e+30]]
[[ -5.06844548e+33  -5.09180325e+32]]
[[  3.99175422e+35  -5.09180325e+32]]
[[  3.99175422e+35   4.01015009e+34]]
[[ -3.14378478e+37   4.01015009e+34]]
[[ -3.14378478e+37  -3.15827282e+36]]
[[  2.47594973e+39  -3.15827282e+36]]
[[  2.47594973e+39   2.48736006e+38]]
[[ -1.94998305e+41   2.48736006e+38]]


In [280]:
print(theta,cost)

[[ -1.94998305e+41  -1.95896949e+40]] [  1.12709150e+52   6.99096623e+55   4.33625919e+59   2.68963447e+63
   1.66828902e+67   1.03478308e+71   6.41840841e+74   3.98112099e+78
   2.46935429e+82   1.53165670e+86]


J = (1 / (2*m) ) * sum(((X * theta)-y).^2);

In [ ]:
Y.mean()

In [281]:
%quickref

In [282]:
%%python3

UsageError: %%python3 is a cell magic, but the cell body is empty.


In [283]:
alias

Total number of aliases: 12


[('cat', 'cat'),
 ('cp', 'cp'),
 ('ldir', 'ls -F -o --color %l | grep /$'),
 ('lf', 'ls -F -o --color %l | grep ^-'),
 ('lk', 'ls -F -o --color %l | grep ^l'),
 ('ll', 'ls -F -o --color'),
 ('ls', 'ls -F --color'),
 ('lx', 'ls -F -o --color %l | grep ^-..x'),
 ('mkdir', 'mkdir'),
 ('mv', 'mv'),
 ('rm', 'rm'),
 ('rmdir', 'rmdir')]

In [284]:
x.append  x.real.

SyntaxError: invalid syntax (<ipython-input-284-445473ed5f9c>, line 1)

In [286]:
x=10


In [ ]:
x.real.

In [ ]:
X[]

In [ ]:
pd.DataFrame(np.random.randn(10, 5))

In [ ]:
import random  #importing random library to generate random number
random.seed(5) #This function maps a particular random number with the seed argument mentioned. All random numbers called after the seeded value returns the mapped number.

In [ ]:
x = [random.randint(-100,100) for i in range(1000)] #Return random integer in range [a, b], including both end points.

In [ ]:
help(random.random)

In [ ]:
x

In [ ]:
df = pd.DataFrame(np.random.randn(100, 4), columns=list('ABCD')df = pd.DataFrame(np.random.randint(0,100,size=(100, 4)), columns=list('ABCD'))

In [ ]:
X = pd.DataFrame(np.random.randint(0,100,size=(100, 4), columns=list('ABCD')))
X

In [ ]:
df = pd.DataFrame(np.random.randn(0,100,size=(100)),np.random.randn(0,100))
df

In [ ]:
np.random.randint(0,100,size=(100, 3))

In [ ]:
People also ask
What is gradient descent algorithm?
What is stochastic gradient descent?
Stochastic gradient descent (often shortened in SGD), also known as incremental gradient descent, is a stochastic approximation of the gradient descent optimization method for minimizing an objective function that is written as a sum of differentiable functions.
Stochastic gradient descent - Wikipedia
https://en.wikipedia.org/wiki/Stochastic_gradient_descent
Search for: What is stochastic gradient descent?
What is back propagation?
The backward propagation of errors, or backpropagation, is a common method of training artificial neural networks and used in conjunction with an optimization method such as gradient descent. The algorithm repeats a two phase cycle, propagation and weight update.
Backpropagation - Wikipedia
https://en.wikipedia.org/wiki/Backpropagation
Search for: What is back propagation?
What is gradient boosting?
Gradient boosting is a machine learning technique for regression and classification problems, which produces a prediction model in the form of an ensemble of weak prediction models, typically decision trees.
Gradient boosting - Wikipedia
https://en.wikipedia.org/wiki/Gradient_boosting
Search for: What is gradient boosting?
What is hinge loss?
In machine learning, the hinge loss is a loss function used for training classifiers. The hinge loss is used for "maximum-margin" classification, most notably for support vector machines (SVMs).
Hinge loss - Wikipedia
https://en.wikipedia.org/wiki/Hinge_loss
Search for: What is hinge loss?
What is the learning rate?
Learning rate is a decreasing function of time. Two forms that are commonly used are a linear function of time and a function that is inversely proportional to the time t. These are illustrated in the Figure 2.7. ... The learning is usually performed in two phases.
Learning rate
users.ics.aalto.fi/jhollmen/dippa/node22.html
Search for: What is the learning rate?
What is Delta rule in neural network?
In machine learning, the delta rule is a gradient descent learning rule for updating the weights of the inputs to artificial neurons in a single-layer neural network. It is a special case of the more general backpropagation algorithm.
Delta rule - Wikipedia
https://en.wikipedia.org/wiki/Delta_rule
Search for: What is Delta rule in neural network?
What is single layer feedforward neural network?
What is Xgboost?
What is adaboost?
What is the use of SVM algorithm?
What is a Softmax?
What is dropout in neural networks?
What is a convolutional neural network?
What is the use of weights in neural network?
What is activation function in artificial neural network?